version: '3'

services:
  redis:
    image: redis
    container_name: cache_redis
    # image: 'redis:5-alpine'
    # command: redis-server --requirepass Redis2019!
    command: redis-server 
    ports:
      - "6379:6379"
    volumes:
      # Linux
      #- 'redis:/data'
      #- /home/axel/Dev/Docker/redis/data:/var/lib/redis/data
      
      # MacOS
      - /Users/axel/Dev/docker/redis/data:/var/lib/redis/data
      