version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: demo123
      #MONGO_INITDB_DATABASE: project
    ports:
      - "27017:27017"
    volumes:
      # linux 
      - /home/axel/Dev/docker/mongo:/data/db
      # MacOS
      # - /Users/axel/Dev/docker/mongo:/data/db
    networks:
      - mongo-network
  
  mongo-express:
    container_name: mongo_express 
    #image: mongo-express
    image: mongo-express:latest
    #restart: always
    #links:
    #  - mongo
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL:  mongodb://root:demo123@mongo:27017
      ME_CONFIG_BASICAUTH_USERNAME: axel
      ME_CONFIG_BASICAUTH_PASSWORD: demo123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: demo123
      #ME_CONFIG_MONGODB_SERVER: mongo
      #ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin 
    networks:
      - mongo-network
      
networks: 
    mongo-network:
      driver: bridge