version: '3'

services:
  mongo:
    image: mongo
<<<<<<< HEAD
    container_name: db_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: demo123
    ports:
      - "27017:27017"
    volumes:
      - /home/axel/Dev/docker/mongo:/data/db
=======
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: demo123
      #MONGO_INITDB_DATABASE: project
    ports:
      - "27017:27017"
    volumes:
      # linux 
      #- /home/axel/Dev/docker/mongo:/data/db
      # MacOS
       - /Users/axel/Dev/docker/mongo:/data/db
>>>>>>> 72b366162181ac6fc608dddc71cb37c4bfc79705
    networks:
      - mongo-network
  
  mongo-express:
<<<<<<< HEAD
    container_name: mongo_express
    image: mongo-express:latest
    #restart: always
    #links:
    #  - mongo
    depends_on:
      - mongo
    ports:
      #- 8082:8081
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL:  mongodb://root:demo123@mongo:27017
      ME_CONFIG_BASICAUTH_USERNAME: axel
      ME_CONFIG_BASICAUTH_PASSWORD: demo123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: demo123
    networks:
      - mongo-network


=======
    container_name: mongo_express 
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: axel
      ME_CONFIG_BASICAUTH_PASSWORD: demo123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: demo123
      #ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin  
    depends_on:
      - mongo
    links:
      - mongo
    networks:
      - mongo-network

>>>>>>> 72b366162181ac6fc608dddc71cb37c4bfc79705
networks: 
    mongo-network:
      driver: bridge