 
version: '3'

services:
  mongo-express:
    container_name: db_mongo
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: axel
      ME_CONFIG_BASICAUTH_PASSWORD: demo123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: demo123
    links:
      - mongo
    networks:
      - mongo-network

  mongo:
    image: mongo
    container_name: mongo_express
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: demo123
    ports:
      - "27017:27017"
    volumes:
      - /home/axel/Dev/docker/mongo:/data/db
    networks:
      - mongo-network

networks: 
    mongo-network:
      driver: bridge