version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "Mysql2019"
      MYSQL_DATABASE: "sotnop"
    ports:
      - "3306:3306"
    volumes:
      - /home/axel/Dev/docker/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 8989:8080
    networks:
      - mysql-compose-network

networks: 
  mysql-compose-network:
    driver: bridge
     