version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "ltda_emprestimos"
    ports:
      - "3307:3306"
    volumes:
      - /home/axel/Dev/docker/mysql:/var/lib/mysql
      # - /Users/axel/Dev/docker/mysql:/var/lib/mysql
    networks:
      - mysql-net

  adminer:
    image: adminer
    ports:
      - 8989:8080
    networks:
      - mysql-net

networks: 
  mysql-net:
    driver: bridge
     