version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "766312"
      MYSQL_DATABASE: "dentallifeapp"
    ports:
      - "3306:3306"
    volumes:
      - /Users/axel/Dev/docker/mysql:/var/lib/mysql
    networks:
      - mysql-network

  adminer:
    image: adminer
    ports:
      - 8989:8080
    networks:
      - mysql-network

networks: 
  mysql-network:
    driver: bridge
     