version: "3.7"

networks:
  main-network:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql_db
    user: root
    ports:
      - "1433:1433"
    environment:
      SA_USERNAME: sa
      SA_PASSWORD: Proj@2501
      ACCEPT_EULA: Y
      MSSQL_AGENT_ENABLED: 'true'
    volumes:
      - /home/axel/Dev/docker/mssql/data:/var/opt/mssql/data
      - /home/axel/Dev/docker/mssql/backup:/var/opt/mssql/Backup
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"