version: "3.7"

networks:
  main-network:

services:
  mssql:
    image: metaskills/mssql-server-linux-tinytds:2017-GA
    container_name: mssql_tinytds
    ports:
      - "1433:1433"
    environment:
      SA_USERNAME: sa
      SA_PASSWORD: Dev1234!
      ACCEPT_EULA: Y
      MSSQL_AGENT_ENABLED: 'true'
    networks:
      - main-network