version: '3'

services:
  db-postgres:
    image: postgres
    container_name: db_postgres
    # restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432" 
    volumes:
      # linux
      - /home/axel/Dev/docker/postgres/data:/var/lib/postgresql/data 
      
      # MacOS
      # - /Users/axel/Dev/docker/postgres/data:/var/lib/postgres/data
      
      # windows
      #- /home/axel/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-net
      
  db-pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL    : "axelpatton@gmail.com"
      PGADMIN_DEFAULT_PASSWORD : "demo123456"
    ports:
      - "16543:80"
    depends_on:
      - db-postgres
    networks:
      - postgres-net

networks: 
  postgres-net:
    driver: bridge
