version: '3'

services:
  db-postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432" 
    volumes:
      # - /home/axel/Dev/docker/postgres/data:/var/lib/postgresql/data 
      - /Users/axel/Dev/docker/postgres/data:/var/lib/postgres/data
      #- /home/axel/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  db-pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL    : "axelpatton@gmail.com"
      PGADMIN_DEFAULT_PASSWORD : "pg12345"
    ports:
      - "16543:80"
    depends_on:
      - db-postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
