version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    container_name: mysql_db5
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "loja_meno"
      #MYSQL_ROOT_HOST: ${DB_HOST}
      #MYSQL_USER: ${DB_USER}
      #MYSQL_PASSWORD: "root"
    ports:
      - "3307:3306"
    volumes:
      # linux
      #- /home/axel/Dev/docker/mysql:/var/lib/mysql
      # macos
      #- /Users/axel/Dev/docker/mysql:/var/lib/mysql
    networks:
      - mysql-net

  adminer:
    image: adminer
    container_name: mysql_adminer
    ports:
      - 8989:8080
    networks:
      - mysql-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - mysqlsrv
    environment:
      - PMA_HOST=mysqlsrv # Note the "fullstack-mysql". Must be the name of the what you used as the mysql service.
      - PMA_USER=axel
      - PMA_PORT=8083
      - PMA_PASSWORD=demo1234
    ports:
      - 9090:80
    restart: always
    networks:
      - mysql-net

networks:
  mysql-net:
    driver: bridge