version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    container_name: mysql_db5
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "loja_meno"
    ports:
      - "3307:3306"
    volumes:
      # linux
      #- /home/axel/Dev/docker/mysql:/var/lib/mysql
      # macos
      - /Users/axel/Dev/docker/mysql:/var/lib/mysql
    networks:
      - mysql-net

  adminer:
    image: adminer
    container_name: mysql_adminer
    ports:
      - 8989:8080
    networks:
      - mysql-net

networks: 
  mysql-net:
    driver: bridge