version: '3'

services:
  redis:
    # image: redis/redis-stack-server:7.2.0-v6
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

volumes:
  redis_data: