version: '3.4'

services:
  oracle-db:
    container_name: app_oracle_11g
    image: oracleinanutshell/oracle-xe-11g
    privileged: true
    ports:
      - 1521:1521
      - 49161:1521
      - 5500:5500
      #- 8080:8080
    environment:
      - ORACLE_SID=XE
      - ORACLE_PDB=XE
    #  - ORACLE_ALLOW_REMOTE=true
    volumes:
      - db-vol:/opt/oracle/oradata

volumes:
 db-vol:

